# Generated by Django 4.2.7 on 2023-11-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('comment_text', models.TextField()),
                ('sentiment_score', models.FloatField()),
            ],
        ),
    ]
